artipie/rpm-adapter

- pom.xml
- src/main/java/com/yegor256/rpm/Primary.java
- src/test/java/com/yegor256/rpm/RpmITCase.java
> Primary xml generation improvements

- .gitignore
- .rultor.yml
- pom.xml
- src/main/java/com/artipie/rpm/Checksum.java
- src/main/java/com/artipie/rpm/Filelists.java
- src/main/java/com/artipie/rpm/Other.java
- src/main/java/com/artipie/rpm/Primary.java
- src/main/java/com/artipie/rpm/ReactiveLock.java
- src/main/java/com/artipie/rpm/Repomd.java
- src/main/java/com/artipie/rpm/Rpm.java
- src/main/java/com/artipie/rpm/SynchronousAct.java
- src/main/java/com/artipie/rpm/Update.java
- src/test/java/com/artipie/rpm/RpmITCase.java
- src/test/java/com/artipie/rpm/RpmTest.java
#20 - upgraded to the latest parent pom and ASTO lib
> Upgraded to latest parent pom and asto lib

- src/main/java/com/artipie/rpm/NamingPolicy.java
- src/main/java/com/artipie/rpm/Repomd.java
- src/main/java/com/artipie/rpm/Rpm.java
- src/test/java/com/artipie/rpm/RpmITCase.java
- src/test/java/com/artipie/rpm/RpmTest.java
> Rpm prefix support

- pom.xml
- src/main/java/com/artipie/rpm/Repomd.java
- src/main/java/com/artipie/rpm/Update.java
- src/test/java/com/artipie/rpm/RpmITCase.java
- src/test/resources/log4j.properties
#26 - fixed `repomd.xml` file updating, updating ASTO version to fix the bug artipie/asto#91 and using blocking implementation of storage to fix repomd bugs
> Fixed repomd

- src/main/java/com/artipie/rpm/Rpm.java
- src/test/java/com/artipie/rpm/RpmITCase.java
#24 - added additional method to perform batch update for all rpm files in repository.
> Batch update by repository key

- src/main/java/com/artipie/rpm/RepoXml.java
- src/test/java/com/artipie/rpm/RepoXmlTest.java
Implemented unit test for Repomd: #35
> resolve #35

- pom.xml
- src/test/java/com/artipie/rpm/PrimaryTest.java
- src/test/java/com/artipie/rpm/RpmITCase.java
- src/test/java/com/artipie/rpm/UpdateTest.java
> update tests to JUnit 5

- src/main/java/com/artipie/rpm/Repomd.java
- src/test/java/com/artipie/rpm/RpmTest.java
> Avoid to upload unused XML files to storage

- pom.xml
- src/test/java/com/artipie/rpm/RpmITCase.java
> Start docker for tests with testcontainers

- src/main/java/com/artipie/rpm/Repomd.java
This is for #41, I believe more can be done so I added another todo.
> #41 - Refactor Repomd.performUpdate for clarity

- src/main/java/com/artipie/rpm/meta/XmlFile.java
- src/main/java/com/artipie/rpm/meta/XmlFilelists.java
- src/main/java/com/artipie/rpm/meta/XmlOthers.java
- src/main/java/com/artipie/rpm/meta/XmlPrimary.java
- src/main/java/com/artipie/rpm/meta/XmlRepomd.java
This is for #81. Even though this PR seems big, most of the changes are removed similar code from 3 classes.
I also added todos to continue the work of improving the design.
>  Factor common code around Xml file writing

- src/main/java/com/artipie/rpm/pkg/MetadataFile.java
- src/main/java/com/artipie/rpm/pkg/PackageOutput.java
- src/test/java/com/artipie/rpm/pkg/MetadataFileTest.java
- src/test/java/com/artipie/rpm/pkg/package-info.java
> Create test for MetadataFile

- src/main/java/com/artipie/rpm/meta/XmlFilelists.java
- src/test/java/com/artipie/rpm/meta/XmlFilelistsTest.java
- src/test/java/com/artipie/rpm/meta/package-info.java
> Add test for XmlFilelists

- pom.xml
Update parent pom version for #101
> #101 update Junit

- src/main/java/com/artipie/rpm/meta/XmlPrimary.java
- src/test/java/com/artipie/rpm/meta/XmlPrimaryTest.java
> Add test for XmlPrimary

- src/main/java/com/artipie/rpm/pkg/FilePackage.java
- src/main/java/com/artipie/rpm/pkg/HeaderTags.java
- src/main/java/com/artipie/rpm/pkg/Package.java
> Extract header into its own interface

- src/main/java/com/artipie/rpm/Repository.java
- src/main/java/com/artipie/rpm/meta/XmlFile.java
- src/main/java/com/artipie/rpm/pkg/MetadataFile.java
- src/main/java/com/artipie/rpm/pkg/PackageOutput.java
- src/test/java/com/artipie/rpm/RpmITCase.java
This is for #86. We still need to wait for CI to pass to validate it's ok.
> Fix error during RpmITCase tests on Windows

- pom.xml
- src/main/java/com/artipie/rpm/http/RpmSlice.java
- src/main/java/com/artipie/rpm/http/package-info.java
#96 - added  HTTP endpoints for RPM repository
> RPM HTTP API

- src/main/java/com/artipie/rpm/FileChecksum.java
- src/main/java/com/artipie/rpm/pkg/FilePackage.java
- src/test/java/com/artipie/rpm/FileChecksumTest.java
#125 - flipping and clearing buffer when calculating checksum
> Calculate checksum correctly

- .github/workflows/release-cli.yml
> Release CLI tool on tag push

- src/main/java/com/artipie/rpm/ModifiableRepository.java
- src/main/java/com/artipie/rpm/Rpm.java
- src/main/java/com/artipie/rpm/meta/XmlPrimary.java
- src/main/java/com/artipie/rpm/meta/XmlPrimaryChecksums.java
- src/main/java/com/artipie/rpm/pkg/FilelistsOutput.java
- src/main/java/com/artipie/rpm/pkg/ModifiableMetadata.java
- src/main/java/com/artipie/rpm/pkg/OthersOutput.java
- src/main/java/com/artipie/rpm/pkg/PrimaryOutput.java
- src/test/java/com/artipie/rpm/meta/XmlPrimaryChecksumsTest.java
For #124 I've tried implement updating metadata for changed packages only.
> #124 update metadata incrementally

- pom.xml
- src/main/java/com/artipie/rpm/meta/XmlPrimaryMaid.java
- src/main/java/com/artipie/rpm/pkg/PrimaryOutput.java
- src/test/java/com/artipie/rpm/meta/XmlPrimaryMaidTest.java
- src/test/resources-binary/repodata/primary.xml.example.first
- src/test/resources-binary/repodata/primary.xml.example.second
For #138 created `XmlPrimaryMaid` that can clean packages from primary.xml without keeping whole xml in memory.
> Clean packages from primary.xml

- pom.xml
- src/main/java/com/artipie/rpm/meta/XmlMaid.java
- src/main/java/com/artipie/rpm/pkg/FilelistsOutput.java
- src/main/java/com/artipie/rpm/pkg/OthersOutput.java
- src/test/java/com/artipie/rpm/meta/ByPkgidAttrTest.java
- src/test/resources-binary/repodata/filelists.xml.example.first
- src/test/resources-binary/repodata/other.xml.example.second
For #136 (and for #135) I've created class to remove data about packages from other.xml and filelist.xml by `pkgid` attribute from `package` tag.
> For #136: remove packages by pkgid

- src/main/java/com/artipie/rpm/meta/XmlFile.java
- src/main/java/com/artipie/rpm/meta/XmlFilelists.java
- src/main/java/com/artipie/rpm/meta/XmlOthers.java
- src/main/java/com/artipie/rpm/meta/XmlPackagesFile.java
- src/test/java/com/artipie/rpm/meta/XmlPackagesFileTest.java
Resolving issue #104 
Added a puzzle for adding additional namespaces in xml.
> #104 - Add XmlPackagesFile

- src/main/java/com/artipie/rpm/Repository.java
- src/main/java/com/artipie/rpm/Rpm.java
- src/main/java/com/artipie/rpm/meta/XmlPrimary.java
- src/main/java/com/artipie/rpm/misc/UncheckedConsumer.java
- src/main/java/com/artipie/rpm/misc/UncheckedFunc.java
- src/main/java/com/artipie/rpm/misc/package-info.java
- src/main/java/com/artipie/rpm/pkg/FilePackage.java
- src/main/java/com/artipie/rpm/pkg/MetadataFile.java
- src/main/java/com/artipie/rpm/pkg/PackageOutput.java
- src/main/java/com/artipie/rpm/pkg/ParsedFilePackage.java
#148 - parallel processing of RPM package metadata parsing and parallel update of metadata files
> Parallel processing

- .github/workflows/integration-test.yml
- .github/workflows/maven.yml
- src/main/java/com/artipie/rpm/files/Gzip.java
- src/test/java/com/artipie/rpm/RpmITCase.java
- src/test/java/com/artipie/rpm/files/GzipTest.java
- src/test/java/com/artipie/rpm/files/TestBundle.java
- src/test/resources/log4j.properties
#151 - using test bundle for RPM integration tests, added CI workflow for this test
> Using test bundle in integration test

- src/test/java/com/artipie/rpm/RpmITCase.java
For #85:
-  added test for repomd.xml update
- left puzzle for implementing the update test for the rest of files
> For #85: added test for repomd.xml update

- pom.xml
- src/main/java/com/artipie/rpm/meta/XmlAlter.java
- src/main/java/com/artipie/rpm/meta/XmlRepomd.java
- src/test/java/com/artipie/rpm/meta/XmlFilelistsTest.java
- src/test/java/com/artipie/rpm/meta/XmlOthersTest.java
- src/test/java/com/artipie/rpm/meta/XmlPrimaryTest.java
- src/test/java/com/artipie/rpm/pkg/MetadataFileTest.java
For #161 corrected puzzle and added jacoco.
> For #161 CI fixed

- .github/workflows/pdd.yml
- .github/workflows/xcop.yml
#161 - some minor improvements of actions checks
> Github actions check improvements

- src/main/java/com/artipie/rpm/meta/XmlFile.java
- src/main/java/com/artipie/rpm/meta/XmlOthers.java
- src/main/java/com/artipie/rpm/meta/XmlPackagesFile.java
- src/main/java/com/artipie/rpm/meta/XmlPrimary.java
This is for #147 
This also fixes some small bugs I found around (see independent commits).
> XmlPrimary uses XmlPackagesFile

- src/main/java/com/artipie/rpm/Rpm.java
- src/test/java/com/artipie/rpm/RpmITCase.java
#182 - cleanup old metadata file on batchUpdate complete
> Cleanup on complete

- src/test/java/com/artipie/rpm/meta/XmlFilelistsTest.java
For #107: added filelists.xml content assertions
> For #107: added filelists.xml content assertions

- src/test/java/com/artipie/rpm/meta/XmlOthersTest.java
For #130: Removed stale puzzle for #130
> For #130: puzzle removal

- src/main/java/com/artipie/rpm/Rpm.java
- src/main/java/com/artipie/rpm/meta/XmlOthers.java
- src/main/java/com/artipie/rpm/meta/XmlPackage.java
- src/main/java/com/artipie/rpm/meta/XmlPrimary.java
- src/main/java/com/artipie/rpm/meta/XmlPrimaryMaid.java
- src/main/java/com/artipie/rpm/pkg/FilelistsOutput.java
- src/main/java/com/artipie/rpm/pkg/MetadataFile.java
- src/main/java/com/artipie/rpm/pkg/OthersOutput.java
- src/main/java/com/artipie/rpm/pkg/PackageOutput.java
- src/main/java/com/artipie/rpm/pkg/PrimaryOutput.java
- src/test/java/com/artipie/rpm/meta/XmlPackagesFileTest.java
- src/test/java/com/artipie/rpm/pkg/MetadataFileTest.java
- src/test/java/com/artipie/rpm/pkg/ModifiableMetadataTest.java
Got rig of string metadata filenames and tags usages with the help of `XmlPackage` enum for #193 and #194.
> For #193: XmlPackage usages

- src/main/java/com/artipie/rpm/meta/XmlMetaJoin.java
- src/test/java/com/artipie/rpm/meta/XmlMetaJoinITCase.java
- src/test/java/com/artipie/rpm/meta/XmlMetaJoinTest.java
- src/test/java/com/artipie/rpm/meta/XmlStreamJoin.java
- src/test/java/com/artipie/rpm/meta/XmlStreamJoinTest.java
For #201 I've moved xml  join stream implementation to test scope, extracted tests for this class and added one more test for xml join with buffered reader.
> Move xml stream join #201

- src/main/java/com/artipie/rpm/Rpm.java
- src/test/java/com/artipie/rpm/RpmTest.java
> #218 - Ignore invalid packages on update

- src/main/java/com/artipie/rpm/meta/ChangelogEntry.java
- src/test/java/com/artipie/rpm/meta/ChangelogEntryTest.java
Part of #191 
Added ChangelogEntry class to parse changelog strings
> #191 - Added ChangelogEntry with partial implementation

- src/main/java/com/artipie/rpm/Rpm.java
For #224 I've extracted repeating to methods.
> #224 - extract repeating code to methods

- src/main/java/com/artipie/rpm/misc/FileInDir.java
- src/test/java/com/artipie/rpm/misc/FileInDirTest.java
For #226 created class to search for the file by substring in the directory.
> #226 - class to find file in directory

- pom.xml
- src/main/java/com/artipie/rpm/http/RpmSlice.java
- src/main/java/com/artipie/rpm/http/RpmUpload.java
- src/test/java/com/artipie/rpm/http/RpmUploadRequestTest.java
- src/test/java/com/artipie/rpm/http/RpmUploadTest.java
For #235 I've implemented RpmUpload and added todo to continue.
> #253 - RpmUpload implemented

- src/main/java/com/artipie/rpm/Rpm.java
- src/test/java/com/artipie/rpm/RpmITCase.java
- src/test/java/com/artipie/rpm/RpmTest.java
> #263 - rename rpm method

- src/test/java/com/artipie/rpm/RpmITCase.java
- src/test/java/com/artipie/rpm/RpmTest.java
- src/test/java/com/artipie/rpm/TestRpm.java
> (#248) - Use TestRpm in tests

- src/main/java/com/artipie/rpm/Rpm.java
- src/main/java/com/artipie/rpm/misc/FileInDir.java
- src/test/java/com/artipie/rpm/meta/XmlMetaJoinITCase.java
- src/test/java/com/artipie/rpm/misc/FileInDirTest.java
This is for #257. I've added extra tests also to validate my understanding of the expected behaviour of the class.
> (#257) - Use FileInDir wherever possible

- pom.xml
- src/main/java/com/artipie/rpm/http/RpmUpload.java
- src/test/java/com/artipie/rpm/http/RpmUploadRequestTest.java
Part of #260 
Added override param parsing to RpmUpload.Request
> #260 - Added override param parsing to RpmUpload.Request

- README.md
> #73 - update readme

- src/main/java/com/artipie/rpm/http/RpmUpload.java
- src/test/java/com/artipie/rpm/http/RpmUploadRequestTest.java
Part of #271 
Added skip_update param reading to `RpmUpload.Request` along with tests
> #271 - Added skip_update param reading to RpmUpload.Request

- src/main/java/com/artipie/rpm/RpmOptions.java
Clean irrelevant puzzle for #281
> Clean irrelevant puzzle

- src/main/java/com/artipie/rpm/http/RpmUpload.java
- src/test/java/com/artipie/rpm/http/RpmUploadTest.java
Closes #271 
`skip_update` parameter supported in `RpmUpload`, tests added
> #271 - Skip update support in RpmUpload

- src/main/java/com/artipie/rpm/RepoConfig.java
- src/main/java/com/artipie/rpm/Rpm.java
- src/main/java/com/artipie/rpm/http/RpmSlice.java
- src/main/java/com/artipie/rpm/http/RpmUpload.java
- src/test/java/com/artipie/rpm/http/RpmSliceITCase.java
- src/test/java/com/artipie/rpm/http/RpmSliceYumITCase.java
- src/test/java/com/artipie/rpm/http/RpmUploadTest.java
For #286 I've created `Simple` implementation of `RepoConfig` and added as parameter to `Rpm` and `RpmSlice`.
> #286 - RepoConfig simple implementation and usage in Rpm

- pom.xml
- src/main/java/com/artipie/rpm/RepoConfig.java
- src/main/java/com/artipie/rpm/RpmOptions.java
- src/test/java/com/artipie/rpm/RepoConfigFromYamlTest.java
Implemented `RepoConfig.FromYaml` for #287.
> #287 - RepoConfig.FromYaml implemented

- pom.xml
Excluded resources to fix release.
> Try exclude resources

- src/test/java/com/artipie/rpm/TestRpm.java
- src/test/java/com/artipie/rpm/http/RpmSliceITCase.java
> (#265) - Add TestRpm.name()

- pom.xml
- src/main/java/com/artipie/rpm/pkg/Checksum.java
- src/test/java/com/artipie/rpm/meta/XmlRepomdTest.java
For #168 I've created test for `XmlRepomd` and added simple implementation of `Checksum`.
> #168 - Test for XmlRepomd

- src/main/java/com/artipie/rpm/pkg/FilePackage.java
- src/main/java/com/artipie/rpm/pkg/PackageOutput.java
- src/test/java/com/artipie/rpm/TestRpm.java
- src/test/java/com/artipie/rpm/pkg/FilePackageTest.java
Created `FilePackageTest` for #154.
> #154 - test for FilePackage

- src/main/java/com/artipie/rpm/meta/PackagesCount.java
- src/test/java/com/artipie/rpm/meta/PackagesCountTest.java
Part of #299 
Added PackagesCount class along with tests
> #299 - Added PackagesCount class

- src/test/java/com/artipie/rpm/hm/NodeHasPkgCount.java
- src/test/java/com/artipie/rpm/hm/NodeHasPkgCountTest.java
- src/test/java/com/artipie/rpm/pkg/ModifiableMetadataTest.java
For #307 I've finished `NodeHasPkgCount` implementation and used it in some test. Added todo to continue.
> #307 - NodeHasPkgCount fully implemented

- src/main/java/com/artipie/rpm/ModifiableRepository.java
- src/main/java/com/artipie/rpm/NamingPolicy.java
- src/main/java/com/artipie/rpm/Repository.java
- src/main/java/com/artipie/rpm/Rpm.java
- src/main/java/com/artipie/rpm/meta/XmlRepomd.java
- src/main/java/com/artipie/rpm/pkg/Metadata.java
- src/main/java/com/artipie/rpm/pkg/MetadataFile.java
- src/main/java/com/artipie/rpm/pkg/ModifiableMetadata.java
- src/main/java/com/artipie/rpm/pkg/Repodata.java
- src/test/java/com/artipie/rpm/pkg/MetadataFileTest.java
- src/test/java/com/artipie/rpm/pkg/ModifiableMetadataTest.java
For #315 I've introduced `Repodata` and created `Temp` implementation. Also corrected javadoc in `NamingPolicy` interface.
> #315 - introduced Repodata abstraction

- src/main/java/com/artipie/rpm/Rpm.java
- src/main/java/com/artipie/rpm/pkg/ModifiableMetadata.java
- src/test/java/com/artipie/rpm/RpmTest.java
- src/test/java/com/artipie/rpm/pkg/ModifiableMetadataTest.java
Closes #236: I've made incremental update work on new repository. 
Note that `ModifiableMetadata` will be changed further in #314.
> #236 - incremental update for new repo

- src/test/java/com/artipie/rpm/TestResource.java
- src/test/java/com/artipie/rpm/meta/XmlPrimaryChecksumsTest.java
- src/test/java/com/artipie/rpm/meta/XmlPrimaryMaidTest.java
- src/test/java/com/artipie/rpm/meta/XmlStreamJoinTest.java
- src/test/java/com/artipie/rpm/pkg/ModifiableMetadataTest.java
- src/test/java/com/artipie/rpm/pkg/PrecedingMetadataFromDirTest.java
Closes #319: access test resources via class-loader
> #319 - Access test resources via class-loader

- src/main/java/com/artipie/rpm/pkg/ModifiableMetadata.java
- src/test/java/com/artipie/rpm/pkg/ModifiableMetadataTest.java
- src/test/resources-binary/repodata/other.xml.example
For #314 I've made `ModifiableMetadata` merge and clean only if necessary, added corresponding tests.
> #314 - optimization in ModifiableMetadata

- src/test/java/com/artipie/rpm/hm/StorageHasMetadata.java
Extended java doc for `StorageHasMetadata`.
> StorageHasMetadata javadoc extended

- pom.xml
- src/main/java/com/artipie/rpm/http/RpmSlice.java
- src/test/java/com/artipie/rpm/http/RpmSliceDownloadITCase.java
- src/test/java/com/artipie/rpm/http/RpmSliceITCase.java
- src/test/java/com/artipie/rpm/http/RpmUploadRequestTest.java
- src/test/java/com/artipie/rpm/http/RpmUploadTest.java
Updated http and asto version, used new features where possible.
> Updated http and asto version

- src/main/java/com/artipie/rpm/misc/RpmByDigestCopy.java
- src/test/java/com/artipie/rpm/misc/RpmByDigestCopyTest.java
Part of #318: created class to copy rpms from one storage to another with filter by digest.
> #318 - copy rpms with filter by digest

- src/test/java/com/artipie/rpm/pkg/FilelistsOutputTest.java
- src/test/resources-binary/repodata/abc-filelists.xml.example
- src/test/resources-binary/repodata/libdeflt-filelists.xml.example
For #321 FilelistsOutputTest  added
> #321 FilelistsOutputTest added

- src/test/java/com/artipie/rpm/pkg/OthersOutputTest.java
- src/test/resources-binary/repodata/abc-other.xml.example
- src/test/resources-binary/repodata/libdeflt-other.xml.example
For #320 OthersOutputTest added
> 320 OthersOutputTest added

- src/main/java/com/artipie/rpm/Rpm.java
- src/test/java/com/artipie/rpm/RpmTest.java
Closes #340 
Using lock with expiration for RPM incremental update
> #340 - Using lock with expiration for RPM incremental update

- pom.xml
- src/main/java/com/artipie/rpm/http/RpmSlice.java
- src/test/java/com/artipie/rpm/http/RpmSliceDownloadITCase.java
- src/test/java/com/artipie/rpm/http/RpmSliceITCase.java
Updated http, ppom and asto versions, used permission actions and fixed build.
> Updated dependencies

- src/main/java/com/artipie/rpm/ModifiableRepository.java
Fix javadoc again to [release](https://github.com/artipie/rpm-adapter/pull/367#issue-492317560)
> One more javadoc fix

- pom.xml
- src/main/java/com/artipie/rpm/http/RpmSlice.java
- src/test/java/com/artipie/rpm/http/RpmSliceDownloadITCase.java
- src/test/java/com/artipie/rpm/http/RpmSliceITCase.java
Closes #368 
Upgraded HTTP to 0.16.7, migrated to `BasicAuthSlice`
> #368 - Upgraded HTTP to 0.16.7, migrated to BasicAuthSlice

- src/test/java/com/artipie/rpm/RpmITCase.java
- src/test/java/com/artipie/rpm/RpmTest.java
- src/test/java/com/artipie/rpm/hm/StorageHasRepoMd.java
- src/test/java/com/artipie/rpm/hm/StorageHasRepoMdTest.java
Closes #359 
Extended test for `StorageHasRepoMd` and used this matcher to check repomd in tests.
> #359 - use StorageHasRepoMd

- .gitignore
- README.md
- pom.xml
- src/main/java/com/artipie/rpm/benchmarks/RpmBench.java
- src/main/java/com/artipie/rpm/benchmarks/package-info.java
For #382 - added benchmarks for RPM batchUpdate
metadata generator.
> Added benchmarks for batchUpdate

- pom.xml
Updated testcontainers to fix IT on github actions.
> Update testcontainers to fix IT on github actions

- pom.xml
- run_benchmarks.sh
> Automate benchmarks

- README.md
- src/main/java/com/artipie/rpm/RpmMetadata.java
- src/main/java/com/artipie/rpm/benchmarks/RpmMetadataRemoveBench.java
Part of #388 
Added benchmark for `RpmMetadata.Remove` and updated description in readme.
> Added benchmark for `RpmMetadata.Remove`

- src/main/java/com/artipie/rpm/meta/XmlEvent.java
- src/test/java/com/artipie/rpm/meta/XmlEventPrimaryTest.java
Part of #388 
Added implementation of `XmlEvent` for primary.xml and extracted class to add list of the rpm's file.
> Added implementation of `XmlEvent` for primary.xml

- src/main/java/com/artipie/rpm/meta/MergedPrimaryXml.java
- src/test/java/com/artipie/rpm/meta/MergedPrimaryXmlTest.java
- src/test/resources-binary/repodata/XmlPrimaryCompTest/libdeflt-nginx-promary.xml.example
- src/test/resources-binary/repodata/XmlPrimaryCompTest/libdeflt-primary.xml.example
Part of #388 
Added more tests for `MergedPrimaryXml` and fixed a mistake in the case with duplicated packages.
> Added more tests for MergedPrimaryXml

- src/main/java/com/artipie/rpm/meta/MergedXml.java
- src/main/java/com/artipie/rpm/meta/XmlAlter.java
- src/main/java/com/artipie/rpm/meta/XmlMaid.java
Part of #388 
Added `MergedXml` to merge filelist and other xml. Test will be added later, also, I'm planning to extract interface from `MergedXml` and `MergedPrimaryXml`.
> Created `MergedXml` to merge filelist and other xml

- src/main/java/com/artipie/rpm/meta/MergedPrimaryXml.java
- src/main/java/com/artipie/rpm/meta/MergedXml.java
- src/main/java/com/artipie/rpm/meta/XmlEvent.java
- src/test/java/com/artipie/rpm/meta/XmlEventFilelistsTest.java
- src/test/java/com/artipie/rpm/meta/XmlEventOtherTest.java
- src/test/java/com/artipie/rpm/meta/XmlEventPrimaryTest.java
Part of #388 
Changed `XmlEvent` signature by adding `XMLEventWriter` as method parameter. Thus, I will be able to pass the required implementation to `MergedXml`.
> Changed `XmlEvent` signature

- src/main/java/com/artipie/rpm/meta/MergedXml.java
- src/main/java/com/artipie/rpm/meta/MergedXmlPackage.java
- src/main/java/com/artipie/rpm/meta/MergedXmlPrimary.java
- src/test/java/com/artipie/rpm/meta/MergedXmlPackageTest.java
- src/test/java/com/artipie/rpm/meta/MergedXmlPrimaryTest.java
Part of #388
Extracted `MergedXml` interface and refactored `MergedXmlPackage` and `MergedXmlPrimary` to implement it.
> Extracted `MergedXml` interface

- src/main/java/com/artipie/rpm/benchmarks/RpmMetadataAppendBench.java
Part of #388 
Added benchmark for `RpmMetadata.Append`
> Added benchmark for `RpmMetadata.Append`

- README.md
Part of #388 
Added information about `RpmMetadataAppendBench` into readme.
> Added information about `RpmMetadataAppendBench` into readme

- pom.xml
- src/main/java/com/artipie/rpm/Rpm.java
- src/main/java/com/artipie/rpm/RpmMetadata.java
Closes #410 
Updated asto and used `ArtipieException` in public API methods.
> Updated asto and used `ArtipieException`

- src/main/java/com/artipie/rpm/RpmMetadata.java
- src/main/java/com/artipie/rpm/meta/MergedXml.java
- src/main/java/com/artipie/rpm/meta/MergedXmlPackage.java
- src/main/java/com/artipie/rpm/meta/MergedXmlPrimary.java
- src/main/java/com/artipie/rpm/pkg/InvalidPackageException.java
- src/test/java/com/artipie/rpm/meta/MergedXmlPackageTest.java
- src/test/java/com/artipie/rpm/meta/MergedXmlPrimaryTest.java
Closes #412 
Added parameter to skip invalid packages on update, class to handle exceptions and made `InvalidPackageException` extend `ArtipieException`.
> Added parameter to skip invalid packages on update

- src/main/java/com/artipie/rpm/RpmMetadata.java
- src/main/java/com/artipie/rpm/meta/MergedXmlPackage.java
- src/main/java/com/artipie/rpm/meta/MergedXmlPrimary.java
- src/test/java/com/artipie/rpm/meta/MergedXmlPackageTest.java
- src/test/java/com/artipie/rpm/meta/MergedXmlPrimaryTest.java
Part of #413 
Input stream in `RpmMetadata.MetadataItem` is now optional, corresponding classes also corrected and tested.
> Made input stream in RpmMetadata.MetadataItem optional

- benchmarks/pom.xml
I've corrected comment formatting in benchmark pom xml. Currently, rultor is complaining and I cannot release new version.
> Corrected formatting in xml

- benchmarks/pom.xml
- src/test/java/com/artipie/rpm/RpmMetadataAppendTest.java
Part of #433 
Added tests to reproduce the error
>  Added test with empty rpm list

- benchmarks/pom.xml
- src/main/java/com/artipie/rpm/files/Gzip.java
Fixed "zip slip" vulnerability
> Arbitrary file write during archive extraction

- benchmarks/pom.xml
- pom.xml
Updated asto to resolve dependencies issues.
> Asto update

- src/main/java/com/artipie/rpm/pkg/HeaderTags.java
- src/test/java/com/artipie/rpm/pkg/HeaderTagsTest.java
Part of #503 
Read obsoletes list, its versions and flags from rpm package.
> Read obsoletes list from rpm packages

- src/main/java/com/artipie/rpm/meta/XmlEventPrimary.java
- src/test/resources-binary/XmlEventPrimaryTest/compat_res.xml
Closes #506 
Excluded items from requires, if they were present in provides, corrected corresponding test data.
> Do not write provides into requires

- src/main/java/com/artipie/rpm/meta/XmlEventPrimary.java
- src/test/java/com/artipie/rpm/meta/XmlEventPrimaryTest.java
- src/test/resources-binary/XmlEventPrimaryTest/authconfig_res.xml
Closes #508 
Added conflicts list into primary xml and corresponding tests.
> Write conflicts tag into primary xml

- pom.xml
> fix: do not add test resources into release

- src/main/java/com/artipie/rpm/meta/XmlEventPrimary.java
- src/test/java/com/artipie/rpm/meta/XmlEventPrimaryTest.java
Part of #521 
Added more items to "special excludes from requires" and tests.
> fix: special excludes from requires

- .github/workflows/codecov.yml
- .github/workflows/update-copyright-years.yml
- README.md
- pom.xml
Part of https://github.com/artipie/artipie/issues/1031
Updated readme, added action for year change and corrected codecov action (there is not need to run ITs to measure code coverage).
> fix: actualize readme

- .github/workflows/integration-test.yml
- .github/workflows/maven.yml
- pom.xml
I've corrected java versions in the actions scripts as there is some unknown compilation error on java 11 after the update of eo-yaml. I do not think it's required to support java 11 and figure out the problem. What do you say?
> deps: update eo-yaml
