artipie/rpm-adapter

src/test/java/com/artipie/rpm/RpmTest.java
Resolving issue #32 
* Converting to JUnit 5
* Extracting method for common behavior
* Rid of PMD warning suppression
* Update puzzle for remaining tasks
=> Update RpmTest to Junit5

src/main/java/com/artipie/rpm/Repomd.java
#29 - Changed `Repomd` implementation to generate metadata file names **before** updating `repomd.xml`.
=> Fixed metadata names

src/main/java/com/artipie/rpm/pkg/FilePackage.java, src/test/java/com/artipie/rpm/pkg/FilePackageHeadersTest.java
This is for #75. See discussion there as to why the todo on `FilePackage` was added.
=> Add tests for FilePackage.Headers and more todos

README.md, src/main/java/com/artipie/rpm/Cli.java, src/main/java/com/artipie/rpm/CliArguments.java
For #129 :
- Changed `Cli.java` and `CliArguments.java` to accept `filelists` as parameter
- Included information in  `README.md`
=> For #129: Optional filelists on the command line

src/main/java/com/artipie/rpm/meta/XmlMetaJoin.java, src/main/java/com/artipie/rpm/pkg/ModifiableMetadata.java, src/test/java/com/artipie/rpm/meta/XmlMetaJoinITCase.java, src/test/java/com/artipie/rpm/meta/XmlMetaJoinTest.java, src/test/resources/log4j.properties
Optimized `XmlMetaJoin` by getting rid of xml steams as requested in #200. New implementation works faster:
```
//buffered reader
[DEBUG] main com.artipie.rpm.meta.XmlMetaJoin: /tmp/junit18146090115461577170/repo/fast.filelists.xml and /tmp/junit18146090115461577170/repo/big.filelists.xml merged in 138ms
//xml stream
[DEBUG] main com.artipie.rpm.meta.XmlMetaJoin: /tmp/junit18146090115461577170/repo/stream.filelists.xml and /tmp/junit18146090115461577170/repo/big.filelists.xml merged in 15s
```
For now I've decided to keep xml steams implementation for tests.
=> Xml join optimization

.rultor.yml, src/main/java/com/artipie/rpm/CliArguments.java, src/test/java/com/artipie/rpm/CliArgumentsTest.java
For #113:
- Added `CliArguments` tests for all expected arguments
- Left puzzle for fixing `naming` and `digest` arguments parsing, since they don't work
=> For #113: added CliArguments tests

pom.xml, src/main/java/com/artipie/rpm/meta/XmlMetaJoin.java, src/test/java/com/artipie/rpm/RpmITCase.java, src/test/java/com/artipie/rpm/TimingExtension.java, src/test/java/com/artipie/rpm/meta/XmlMetaJoinITCase.java, src/test/java/com/artipie/rpm/meta/XmlStreamJoin.java
For #203 added `TimingExtension` for junit, used it in itcases and removed logging in main classes.
=> #203 - add timing extension for tests

src/main/java/com/artipie/rpm/pkg/FilePackage.java, src/main/java/com/artipie/rpm/pkg/InvalidPackageException.java, src/test/java/com/artipie/rpm/RpmTest.java, src/test/java/com/artipie/rpm/pkg/FilePackageHeadersTest.java
Part of #190 
Throwing InvalidPackageException when package failed to be parsed.
This is required to distinguish bad package from other problems when package is parsed, such as I/O errors
=> #190 - Throwing InvalidPackageException when package failed to be parsed

pom.xml, src/main/java/com/artipie/rpm/Rpm.java
Restructured `Rpm#updateBatchIncrementally` to get rid of blocking operations for #192.
=> #192 - no blocking operations on incremental update

src/main/java/com/artipie/rpm/meta/ChangelogEntry.java, src/test/java/com/artipie/rpm/meta/ChangelogEntryTest.java
Part of #191 
Added `date` method to `ChangelogEntry` for parsing date from source string
=> #191 - Added date parsing to ChangelogEntry

src/main/java/com/artipie/rpm/ModifiableRepository.java, src/main/java/com/artipie/rpm/Repository.java, src/main/java/com/artipie/rpm/Rpm.java, src/main/java/com/artipie/rpm/pkg/Metadata.java, src/main/java/com/artipie/rpm/pkg/MetadataFile.java, src/main/java/com/artipie/rpm/pkg/ModifiableMetadata.java, src/test/java/com/artipie/rpm/RpmTest.java, src/test/java/com/artipie/rpm/pkg/MetadataFileTest.java, src/test/java/com/artipie/rpm/pkg/ModifiableMetadataTest.java
Part of #230 - create temp dir for metadata on each update. Also, I've corrected old metadata clean up as it does not work on not `ROOT` repositories.
=> #230 - temp dir for metadata

src/main/java/com/artipie/rpm/meta/XmlRepomd.java
Removed puzzle from `XmlRepomd` as it's not relevant anymore.
=> Remove puzzle from XmlRepomd

src/main/java/com/artipie/rpm/pkg/FilePackage.java, src/main/java/com/artipie/rpm/pkg/FilePackageHeader.java, src/test/java/com/artipie/rpm/pkg/ModifiableMetadataTest.java, src/test/java/com/artipie/rpm/pkg/PrimaryOutputTest.java
Closes #278 
Extracted `FilePackageHeader` from `FilePackage`, added usage in tests to reduce code duplication
=> #278 - Extracted FilePackageHeader from FilePackage

src/main/java/com/artipie/rpm/RepoConfig.java, src/test/java/com/artipie/rpm/RepoConfigFromYamlTest.java
I've set `sha256` as default naming policy in yaml configuration.
=> Default naming policy in config from yaml

src/main/java/com/artipie/rpm/meta/PackagesCount.java, src/test/java/com/artipie/rpm/meta/PackagesCountTest.java
Closes #299 
Improvements to `PackagesCount`:
- stop scanning the file if attribute has been found
- better exception when attribute is missing
- negative tests for cases when attribute is not found
=> #299 - Improvements to PackagesCount

src/test/java/com/artipie/rpm/RpmTest.java, src/test/java/com/artipie/rpm/TestRpm.java, src/test/java/com/artipie/rpm/http/RpmUploadTest.java, src/test/java/com/artipie/rpm/pkg/FilePackageTest.java, src/test/java/com/artipie/rpm/pkg/ModifiableMetadataTest.java, src/test/java/com/artipie/rpm/pkg/PrimaryOutputTest.java
Part of #319 - added `path()` method to `TestRpm` and used it instead of `Paths.get()`. Also corrected `RpmTest` to use `TestRpm.Invalid()`.
=> #319 - added path() to TestRpm.java

pom.xml, src/main/java/com/artipie/rpm/Rpm.java, src/main/java/com/artipie/rpm/misc/RpmByDigestCopy.java, src/test/java/com/artipie/rpm/RpmITCase.java
Updated asto and used `PublisherAs` and `KeyLastPart` from the new version to close #333.
=> #333 - use PublisherAs and KeyLastPart from asto

pom.xml, src/main/java/com/artipie/rpm/Rpm.java
Simplified `Rpm#moveRepodataToStorage` to use `SubStorage` instead of `Key` with prefix to close #250.
=> #250 - use substorage

src/main/java/com/artipie/rpm/meta/XmlPrimary.java
I've removed xml-like formatting from javadoc as rultor [failed](https://github.com/artipie/rpm-adapter/pull/364#issuecomment-694154177) to release.
=> Javadoc fix

src/test/java/com/artipie/rpm/hm/StorageHasRepoMd.java, src/test/java/com/artipie/rpm/hm/StorageHasRepoMdTest.java, src/test/resources-binary/repodata/StorageHasRepoMdTest/repomd.xml
Part of #359 
Implemented `StorageHasRepoMd` to verify `repomd.xml` is present and has records about metadata xmls.
=> #359 - Verify repomd.xml

src/main/java/com/artipie/rpm/meta/XmlException.java, src/main/java/com/artipie/rpm/meta/XmlMaid.java, src/main/java/com/artipie/rpm/pkg/FilelistsOutput.java, src/main/java/com/artipie/rpm/pkg/MetadataFile.java, src/main/java/com/artipie/rpm/pkg/OthersOutput.java, src/main/java/com/artipie/rpm/pkg/PrimaryOutput.java, src/test/java/com/artipie/rpm/meta/XmlStreamJoin.java
Closes #323 
Used `XmlException` for any problems with xml metadata instead of `IOException`
=> #323 - use XmlException for errors with xml metadata

src/test/java/com/artipie/rpm/RpmTest.java, src/test/java/com/artipie/rpm/hm/IsXmlEqual.java
Part of #227 
I've upgraded `RpmTest` by creating enum with two updates (incremental and not) and parameterized all tests with this enum. 
Also, for invalid package there are now two tests:
- `doesNotTouchMetadataIfInvalidRpmIsSent` to make sure that metadata stays intact when invalid package is sent to the repo. This test works only with incremental update as usual update actually rewrites all metadata on each update skipping invalid package
- `skipsInvalidPackageOnUpdate` to verify that we simply skip invalid package on update
=> #227 - extend tests with invalid package

pom.xml, src/main/java/com/artipie/rpm/Rpm.java, src/test/java/com/artipie/rpm/RpmTest.java
Part of #227 
Created test to verify that temp dir is cleaned up and fixed `Rpm` to call `onTerminate` on the outer completable.
=> #227 - temp dir is cleaned up

pom.xml, src/main/java/com/artipie/rpm/Rpm.java, src/main/java/com/artipie/rpm/pkg/FilePackage.java, src/main/java/com/artipie/rpm/pkg/ParsedFilePackage.java, src/test/java/com/artipie/rpm/RpmTest.java, src/test/java/com/artipie/rpm/pkg/FilePackageHeadersTest.java, src/test/java/com/artipie/rpm/pkg/FilePackageTest.java, src/test/java/com/artipie/rpm/pkg/OthersOutputTest.java, src/test/java/com/artipie/rpm/pkg/PrimaryOutputTest.java
Part of #376 
Fixed `location` tag in `primary.xml` by providing storage key of the rpm package to headers.
=> #376 - added subdirs to location in primary

src/main/java/com/artipie/rpm/Rpm.java, src/test/java/com/artipie/rpm/RpmTest.java
Closes #376 
Take not root keys into account: when we update rpm repo not by ROOT key (let's call it prefix) and list items from the storage by this prefix, items key includes this prefix which we have to cut from the location as location path should be relative to this prefix.
=> #376 - Take not root keys into account

.gitignore, src/main/java/com/artipie/rpm/benchmarks/RpmBench.java
For #382 - using incremental batch udate for RPM repository,
added proper setup methods for each iteration to copy
bundle repository to memory storage instead of reading from disk.
=> Improved RPM benchmarks

pom.xml, src/main/java/com/artipie/rpm/RpmMetadata.java, src/main/java/com/artipie/rpm/meta/XmlMaid.java, src/main/java/com/artipie/rpm/meta/XmlPrimaryMaid.java
Part of #388 
1) I've found implementations of `XMLEventReader/XMLEventWriter` which work times faster than standard ones - 2 seconds against 4 minutes locally for 86 mb xml file. Tests and benchmarks will be added later.
2) Added skeleton for new sdk API - it will work with streams as our colleagues want. `RpmMetadata` has two classes, one for removing and second for adding info about provided RPM packages.
=> Faster xml event reader and skeleton for new sdk API

src/main/java/com/artipie/rpm/RpmMetadata.java, src/test/java/com/artipie/rpm/RpmMetadataRemoveTest.java
Part of #388 
Implemented `RpmMetadata.Remove` class and added corresponding unit-test. The implementation uses temp file to write an intermediate result. We cannot use Pipied io streams here as operations should be performed one by one.
=> Implemented RpmMetadata.Remove

src/main/java/com/artipie/rpm/RpmMetadata.java, src/main/java/com/artipie/rpm/meta/XmlEvent.java, src/main/java/com/artipie/rpm/pkg/FilePackage.java, src/main/java/com/artipie/rpm/pkg/FilePackageHeader.java, src/test/java/com/artipie/rpm/meta/XmlEventOthersTest.java
Part of #388 
Created `XmlEvent` - interface to add info about rpm package to the writer and first implementation to write `others.xml`.
Also changed `RpmMetadata.Append` signature: digest algorithm is required to calculate rpm checksum, use `FilePackage` is not a good idea as it has its methods that are not suitable for external usage.
=> Created `XmlEvent` and its first implementation

src/main/java/com/artipie/rpm/meta/XmlEvent.java, src/test/java/com/artipie/rpm/meta/XmlEventFilelistsTest.java, src/test/java/com/artipie/rpm/meta/XmlEventOtherTest.java
Part of #388 
Created implementations of `XmlEvent`
- `PackageAndVersion` to add `package` and `version` tags (these tags are used in other and filelists)
- `Filelists` to add rpm item to filelists.xml and corresponding test
Also renamed `XmlEvent.Others` to `XmlEvent.Other` (without `s`) to correspond to xml index file name.
=> Created implementation of `XmlEvent` for filelists.xml

src/main/java/com/artipie/rpm/RpmMetadata.java, src/test/java/com/artipie/rpm/RpmMetadataAppendTest.java
Part of #388 
Implemented `RpmMetadata.Append` and added test.
=> Implemented `RpmMetadata.Append`

src/main/java/com/artipie/rpm/RpmMetadata.java
Part of #388 
Made `RpmMetadata.Append` perform independent operations in parallel.
=> Perform independent operations in parallel

src/main/java/com/artipie/rpm/meta/XmlPrimaryMaid.java, src/test/java/com/artipie/rpm/RpmMetadataRemoveTest.java, src/test/java/com/artipie/rpm/meta/XmlPrimaryMaidTest.java, src/test/resources-binary/repodata/empty/filelists_1.xml.example, src/test/resources-binary/repodata/empty/filelists_2.xml.example, src/test/resources-binary/repodata/empty/primary_1.xml.example, src/test/resources-binary/repodata/empty/primary_2.xml.example, src/test/resources-binary/repodata/primary.xml.example_maid.first, src/test/resources-binary/repodata/primary.xml.example_maid.second
Closes #415 
Corrected `RpmMetadata.Remove()` to work with empty indexes properly.
=> Remove from empty indexes

src/test/java/com/artipie/rpm/RpmMetadataAppendTest.java
Closes #413 
Added test with absent input streams for `RpmMetadata.Append`.
=> Added test with absent input streams for `RpmMetadata.Append`

pom.xml
Closes #423 
Removed `log4j` and excluded `com.fasterxml.jackson.core/jackson-databind`, apache.ant is not in our in pom and vertx is in the text scope.
=> Correct dependencies

benchmarks/pom.xml
Still cannot release the adapter, rultor is complaining to benchmark's pom.
=> Placed `project` tag value in one line in benchmarks pom

benchmarks/pom.xml
Rultor is complaining about absent licence in benchmarks pom, fixed
=> Added licence to benchmarks pom

benchmarks/pom.xml, src/main/java/com/artipie/rpm/RpmMetadata.java, src/main/java/com/artipie/rpm/meta/MergedXml.java, src/main/java/com/artipie/rpm/meta/MergedXmlPackage.java, src/main/java/com/artipie/rpm/meta/MergedXmlPrimary.java, src/main/java/com/artipie/rpm/pkg/FilePackage.java, src/test/java/com/artipie/rpm/RpmMetadataAppendTest.java, src/test/java/com/artipie/rpm/meta/MergedXmlPackageTest.java, src/test/java/com/artipie/rpm/meta/MergedXmlPrimaryTest.java
Part of #428 
Changed `Metadata.Append.perform()` signature, corrected tests and all the code. Added class `RpmItem`, this`Package.Meta` implementation will be used by our colleagues. 
As now rpm file is parsed outside, parameter `skip` to skip invalid packages is not valid, I'll remove in the next PR.
=> Changes `Metadata.Append.perform()` signature

benchmarks/pom.xml, src/main/java/com/artipie/rpm/RpmMetadata.java, src/main/java/com/artipie/rpm/meta/MergedXmlPackage.java, src/main/java/com/artipie/rpm/meta/MergedXmlPrimary.java, src/test/java/com/artipie/rpm/meta/MergedXmlPackageTest.java, src/test/java/com/artipie/rpm/meta/MergedXmlPrimaryTest.java
Part of #428 
As rpm file is parsed outside our sdk, there is no need for `skip` parameter to skip invalid rpm packages. Removed parameter and tests.
=> Parameter skip removed from `RpmMetadata.Append`

benchmarks/pom.xml, benchmarks/src/main/java/com/artipie/rpm/benchmarks/RpmMetadataAppendBench.java
Closes #428 
Corrected `RpmMetadataAppendBench` to work accordingly to new `RpmMetadata.Append()` signature.
=> Corrected `RpmMetadataAppendBench` accordingly signature changes

.github/workflows/benchmarks.yml, benchmarks/results/README.md
Part of artipie/artipie#431
Added action for runnning benchmarks by pushing a new tag which starts from `test`. After check it would be replaced with tag which is required for releasing a new version
=> ci: add action for running benchmarks

benchmarks/LICENSE.header, benchmarks/LICENSE.txt, benchmarks/pom.xml, benchmarks/src/main/java/com/artipie/rpm/RpmBench.java, benchmarks/src/main/java/com/artipie/rpm/RpmMetadataAppendBench.java, benchmarks/src/main/java/com/artipie/rpm/RpmMetadataRemoveBench.java, benchmarks/src/main/java/com/artipie/rpm/package-info.java, pom.xml
Part of artipie/artipie#431
Bumped asto to `v1.8.0`, extracted benchmarks as a separate Maven project
=> deps: bump asto to v1.8.0, extract benchmarks as a module

benchmarks/pom.xml
Bumped asto in benchmarks to `v1.9.0` to use class for exclusion keys
=> dep: bump asto in bench to `v1.9.0`

benchmarks/src/main/java/com/artipie/rpm/RpmBench.java, pom.xml, src/main/java/com/artipie/rpm/Rpm.java, src/test/java/com/artipie/rpm/RpmITCase.java, src/test/java/com/artipie/rpm/RpmTest.java
Part of #440 
Fully remade `Rpm.batchUpdated` not to copy packages and to not work with files:
- `Rpm.batchUpdatedIncrementally` is now deprecated and calls `Rpm.batchUpdated`
- corrected integration test to use `Rpm.batchUpdated`
- simplified `RpmTest` and added test for the case, when packages are removed from repo
=> Do not copy packages in `Rpm.batchUpdated`

src/main/java/com/artipie/rpm/meta/XmlEvent.java
`createrepo` generates duplicates on `rpm:requires` section
if entry provides additional constraints to previously defined item.
Fixed rpm-adapter to provide duplicates with additional constraints
as `createrepo`.
Fix: #490
=> fix: allow duplicates in requires

src/main/java/com/artipie/rpm/RpmMetadata.java, src/main/java/com/artipie/rpm/asto/AstoMetadataAdd.java, src/main/java/com/artipie/rpm/meta/XmlEvent.java, src/main/java/com/artipie/rpm/meta/XmlEventPrimary.java, src/test/java/com/artipie/rpm/meta/MergedXmlPrimaryTest.java, src/test/java/com/artipie/rpm/meta/XmlEventPrimaryTest.java, src/test/resources-binary/AstoMetadataAddTest/primary-res.xml, src/test/resources-binary/XmlEventPrimaryTest/abc_res.xml, src/test/resources-binary/XmlEventPrimaryTest/ant_res.xml, src/test/resources-binary/XmlEventPrimaryTest/felix-framework-res.xml, src/test/resources-binary/XmlEventPrimaryTest/httpd_res.xml
Part of #495 
Added filer to `XmlEvent.Files` to filter items in primary.xml. Also, moved `XmlEvent.Primary` class to upper level as it became too large. Corrected tests.
=> Filter files in primary

pom.xml, src/test/java/com/artipie/rpm/RepoConfigFromYamlTest.java, src/test/java/com/artipie/rpm/RpmOptionsTest.java, src/test/java/com/artipie/rpm/hm/NodeHasPkgCount.java, src/test/java/com/artipie/rpm/hm/NodeHasPkgCountTest.java, src/test/java/com/artipie/rpm/hm/StorageHasMetadata.java, src/test/java/com/artipie/rpm/hm/StorageHasRepoMd.java
We figured out that `Mismatches` (`cactoos-matchers:0.18`) failed to match on Windows
because line separator used in expected mismatch description contained
Unix separator while actual description contained windows separator.
So, we bumped `cactoos-matchers` to version `0.25` and updated all matchers impacted by
what's new in the new version.
Fix: #310
=> fix: enable two tests of NodeHasPkgCountTest on Windows

src/main/java/com/artipie/rpm/meta/XmlEventPrimary.java, src/test/resources-binary/AstoMetadataAddTest/primary-res.xml, src/test/resources-binary/XmlEventPrimaryTest/abc_res.xml, src/test/resources-binary/XmlEventPrimaryTest/httpd_res.xml, src/test/resources-binary/XmlEventPrimaryTest/openssh_res.xml
Part of #489 
Added `libc.so` versions comparison, now only greatest version if written to primary.xml.
=> Write only greatest version of `libc.so` in primary

src/main/java/com/artipie/rpm/meta/XmlEvent.java, src/main/java/com/artipie/rpm/pkg/HeaderTags.java, src/test/java/com/artipie/rpm/pkg/HeaderTagsTest.java, src/test/resources-binary/XmlEventPrimaryTest/authconfig_res.xml
We check now if a file is a `ghost` exactly as it's done in `createrepo` and we add `type=ghost` to its entity if it's true.
As expected, these new changes broke some tests. We fixed them all.
Resolve: #512
=> feat(XmlEvent) : check if primary file is a ghost

pom.xml, src/main/java/com/artipie/rpm/meta/CrCompareDependency.java, src/test/java/com/artipie/rpm/files/TestBundle.java
closes #247 
Replaced semver4j  with maven-artifact.
=> feat: replace semver4j  with maven-artifact

src/main/java/com/artipie/rpm/RpmMetadata.java, src/main/java/com/artipie/rpm/meta/MergedXmlPackage.java, src/main/java/com/artipie/rpm/meta/MergedXmlPrimary.java, src/main/java/com/artipie/rpm/meta/XmlAlter.java, src/main/java/com/artipie/rpm/meta/XmlMaid.java, src/main/java/com/artipie/rpm/meta/XmlPrimaryMaid.java
=> feat: optimization of adapter code

pom.xml, src/main/java/com/artipie/rpm/asto/AstoMetadataRemove.java, src/main/java/com/artipie/rpm/asto/AstoRepoAdd.java, src/main/java/com/artipie/rpm/asto/AstoRepoRemove.java, src/main/java/com/artipie/rpm/http/RpmRemove.java, src/main/java/com/artipie/rpm/http/RpmSlice.java, src/main/java/com/artipie/rpm/http/RpmUpload.java, src/main/java/com/artipie/rpm/meta/PackageInfo.java, src/main/java/com/artipie/rpm/meta/XmlPrimaryMaid.java, src/main/java/com/artipie/rpm/pkg/FilePackage.java, src/main/java/com/artipie/rpm/pkg/Package.java, src/test/java/com/artipie/rpm/asto/AstoMetadataRemoveTest.java, src/test/java/com/artipie/rpm/http/RpmRemoveTest.java, src/test/java/com/artipie/rpm/http/RpmUploadTest.java
=> feat: log upload/remove events
